language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

env:
  - SYMFONY_VERSION=2.3.* DEV=
  - SYMFONY_VERSION=2.4.* DEV=
  - SYMFONY_VERSION=2.5.* DEV=
  - SYMFONY_VERSION=2.6.*@dev DEV=--dev

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} ${DEV} --no-interaction --prefer-dist 
    - composer install --no-interaction --prefer-dist --dev
    - phpunit --self-update

addons:
    code_climate:
        repo_token: 83de4f940c6760d66c95fc929e0950e89ec9edb007f356915720c613fa621b2b 

after_script:
    - php bin/test-reporter
